sudo: false
language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
install:
  - npm i
jobs:
  include:
    - stage: 'Test'
      name: 'Run code linting and test'
      script: npm run lint && npm test
